"""Summary generation service for task runs.

This module provides automatic summary generation after task runs complete.
Summaries are generated by invoking Claude in non-interactive mode with
the task's log data.
"""

import json
import subprocess
import sys
from typing import Optional

from .db_client import DatabaseClient
from .models.task import ScheduledTask
from .output import prettify_output


# Simple prompt for summary generation
SUMMARY_PROMPT = "Summarize the following task execution logs:\n\n"

# Fixed timeout for summary generation (60 seconds)
SUMMARY_TIMEOUT_SECONDS = 60


class SummaryService:
    """Service for generating summaries of task runs."""

    def __init__(self, db_path: str):
        """Initialize the summary service.

        Args:
            db_path: Path to the SQLite database
        """
        self.db_path = db_path
        self.db_client = DatabaseClient(db_path)

    def generate_summary(self, run_id: str) -> None:
        """Generate and store a summary for a task run.

        Retrieves all logs for the run, sends them to Claude for summarization,
        and updates the run record with the summary.

        Args:
            run_id: ID of the run to summarize
        """
        # Get the run to find task details
        run = self.db_client.get_run(run_id)
        if not run:
            return

        # Get the task to find summary_model
        task = self.db_client.get_task(run.task_id)
        if not task:
            self.db_client.update_run(
                run_id, run_summary="Summary generation failed: Task not found"
            )
            return

        # Retrieve all logs for this run
        logs = self.db_client.list_logs(run_id=run_id, limit=10000)
        if not logs:
            self.db_client.update_run(
                run_id, run_summary="No logs found for this run"
            )
            return

        # Format logs as JSON for Claude
        logs_json = json.dumps(
            [
                {
                    "event_type": log.event_type.value,
                    "level": log.level.value,
                    "message": log.message,
                    "details": log.details,
                    "created_at": log.created_at.isoformat(),
                }
                for log in logs
            ],
            indent=2,
        )

        # Invoke Claude for summarization
        try:
            summary = self._invoke_claude_for_summary(
                logs_json=logs_json,
                summary_model=task.summary_model,
                project_path=task.project_path,
            )
            self.db_client.update_run(run_id, run_summary=summary)
        except subprocess.TimeoutExpired:
            self.db_client.update_run(
                run_id, run_summary="Summary generation timed out"
            )
        except Exception as e:
            error_msg = str(e)[:200]
            self.db_client.update_run(
                run_id, run_summary=f"Summary generation failed: {error_msg}"
            )

    def _invoke_claude_for_summary(
        self,
        logs_json: str,
        summary_model: str,
        project_path: str,
    ) -> str:
        """Invoke Claude CLI to generate a summary.

        Args:
            logs_json: JSON-formatted log data
            summary_model: Model to use for summarization
            project_path: Working directory for the invocation

        Returns:
            Summary text extracted from Claude's response

        Raises:
            subprocess.TimeoutExpired: If summarization times out
            Exception: If any other error occurs
        """
        cmd = [
            "claude",
            "--print",
            "--model", summary_model,
            "--output-format", "json",
        ]

        # Build the full prompt
        full_prompt = SUMMARY_PROMPT + logs_json

        # Run Claude with timeout
        process = subprocess.Popen(
            cmd,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            cwd=project_path,
        )

        try:
            stdout, stderr = process.communicate(
                input=full_prompt,
                timeout=SUMMARY_TIMEOUT_SECONDS,
            )
        except subprocess.TimeoutExpired:
            process.kill()
            process.wait()
            raise

        if process.returncode != 0:
            raise RuntimeError(f"Claude exited with code {process.returncode}: {stderr}")

        # Prettify the output to extract the result text
        extracted = prettify_output(stdout)
        summary_text = extracted.get("result") or stdout

        return summary_text


def spawn_summary_generation(
    run_id: str,
    task: ScheduledTask,
    db_path: str,
) -> None:
    """Spawn summary generation in a detached background process.

    Uses subprocess.Popen with start_new_session=True to create a process
    that continues running after the parent exits.

    Args:
        run_id: ID of the run to summarize
        task: Task object (unused, but kept for API consistency)
        db_path: Path to the SQLite database
    """
    subprocess.Popen(
        [
            sys.executable,
            "-c",
            f"from claude_task_scheduler_cli.summary import SummaryService; "
            f"SummaryService('{db_path}').generate_summary('{run_id}')",
        ],
        start_new_session=True,  # Detach from parent process
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
